### ISSUE TITLE
PHP 7.0 required?

### ISSUE THREAD

**Issue by strebl** [tomschlick/laravel-http2-server-push#10]
Hi @tomschlick 

Thanks for your Middleware!
Is there a reason that PHP >= 7.0 is required?

Regards

**Comment by tomschlick** [comment]
It's basically the ability to do return type hints and only have to test on something modern. What version did you have in mind? 

5.6?

**Comment by strebl** [comment]
Sorry for not answering. I missed the email.
Yeah I'm using 5.6. But I'll update. I think it's great to move forward!
