### ISSUE TITLE
Support L5.4

### ISSUE THREAD

**Issue by paulschwarz** [tomschlick/laravel-http2-server-push#12]
The composer file avoids support for 5.4, and rightly so because we're now on mix instead of elixir. Any plans to support this?

**Comment by tomschlick** [comment]
Done https://github.com/tomschlick/laravel-http2-server-push/releases/tag/v0.1.4

**Comment by paulschwarz** [comment]
Thanks, but still a small issue. Laravel 5.4 ships with mix instead of elixir. While it's possible to use either/or, the scheme for mix has changed a little. 

The `elixir()` helper has been replaced by `mix()` and the manifest is in a different path `public/mix-manifest.json`.

An example of a mix manifest is as follows:

```
{
  "/js/app.js": "/js/app.328b215b91136cfd99c0.js",
  "/js/vendor.js": "/js/vendor.d1d8c9b3c0d96d0e6c94.js",
  "/css/app.css": "/css/app.acb9296df976f0a8889c.css",
  "/js/manifest.js": "/js/manifest.d41d8cd98f00b204e980.js"
}
```

And if it helps, here's a link to the new mix method https://github.com/laravel/framework/blob/5.4/src/Illuminate/Foundation/helpers.php#L551-L592

**Comment by tomschlick** [comment]
Any chance you could submit a PR to fix this? I just don't have time today to get it out.

If so, please add a config item for which version of elixir so we can continue to support both.

**Comment by paulschwarz** [comment]
Please include instructions on how to run your tests.

**Comment by paulschwarz** [comment]
See https://github.com/tomschlick/laravel-http2-server-push/pull/13
